# Generated by Django 4.0 on 2022-01-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='wished_item',
            new_name='book',
        ),
    ]
