# Generated by Django 4.0 on 2022-01-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_wished_item_favorite_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
