# Generated by Django 4.0 on 2022-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_favorite_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='is_added',
            field=models.TextField(choices=[('clicked', 'clicked'), ('not clicked', 'not clicked')], default='not clicked'),
        ),
    ]
