# Generated by Django 4.0 on 2022-01-09 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_remove_favorite_is_added_favorite_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorites',
        ),
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
