# Generated by Django 4.0 on 2022-01-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_favorite_favorites_book_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='slug',
        ),
    ]
