# Generated by Django 4.0 on 2022-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_favorite_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorites',
        ),
        migrations.AddField(
            model_name='favorite',
            name='slug',
            field=models.CharField(default=111, max_length=130),
            preserve_default=False,
        ),
    ]
