# Generated by Django 3.2.7 on 2022-01-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20220110_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='comments',
        ),
    ]
