# Generated by Django 3.2.7 on 2022-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_comment_blogcomment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
