# Generated by Django 3.2.7 on 2022-01-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_blogcomment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='text',
        ),
    ]
