# Generated by Django 3.2.7 on 2022-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_blogcomment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='book',
        ),
        migrations.AddField(
            model_name='favorite',
            name='book',
            field=models.ManyToManyField(to='main_app.Book'),
        ),
    ]
