# Generated by Django 3.2.7 on 2022-01-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20220111_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
