# Generated by Django 3.2.7 on 2022-01-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20220112_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
    ]
